language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=travis
services:
  - mongodb

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9a73b97f9099e4b1d7e4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
