language: go

go:
  - 1.7

env:
  - GO_VENDOR=1

cache:
  directories:
    - bower_components
    - node_modules

before_install:
  - nvm --version
  - nvm install 7.2.0
  - node --version && npm --version

install:
  - go get -u github.com/alecthomas/gometalinter
  - go get -v github.com/kardianos/govendor
  - gometalinter -u -i -f
  - govendor sync -v
  - go get -u github.com/stretchr/testify
  - npm install -g yarn
  - yarn install

script:
  - go build
  - go test ./cmd/... ./model/... ./server/...
  - npm test

  - travis_wait 60 gometalinter --vendor --deadline=60m --config=./gometalinter.json ./server/... ./model/... ./cmd/... .
  - npm run lint

  - npm run dist
