language: go

go:
- 1.7

env:
- GO_VENDOR=1
- NODE_ENV=production

cache:
  directories:
  - bower_components
  - node_modules

before_install:
- nvm --version
- nvm install 7.2.0
- node --version && npm --version

install:
- go get -u github.com/alecthomas/gometalinter
- go get -v github.com/kardianos/govendor
- gometalinter -u -i -f
- govendor sync -v
- go get -u github.com/stretchr/testify
- npm install -g yarn
- yarn install

script:
- go build
- go test ./cmd/... ./model/... ./server/...
- npm test
- travis_wait 60 npm run golint
- npm run lint
- npm run archive

deploy:
  provider: releases
  api_key:
    secure: k51K9vGcO8TL9RlrePYbOqXCqsPK1ugVSL9pVHLqn8IfvhbUoL83dXEUdQ8CZpeKVm5LF8IhW6s12ut97ieWCPnSjc01h946mm0U3H2R6WL2z5LjsNRE6BIGIUnPlHOlGl0f602MXAGKJhlv2VmJ0w3Y8Q9RjtqxTKYJ1mFlohN6frdsSfbWmA6FAf2bd3uP5850eXzbfpuDdnvJNBfMwUG1gWKavyNO525Q0rA4z/fcqnwTvX+I8h4FT+5+Yt/bX912VfahHz/8DVvQek8yU/8VF7A4sClXCd23j4p6Pirb0ESk/UldULRHoGc0Q9Yr59ancX3+IM/HyJA+0X1Nta2FCzldYcxMaADi2MEEf0jA1R1MOeXL+Su5nBG1LDR9igSZ0uH5PieecgrSy9nCZldVwoLs1gjD8nfWvvuk4VFr8A6o9JQEdLwlyqf+weW1RignkAkCIakqSXs4tpyct52ybey6k5lVXMcNVhf+XDmWN55htvZYoP01zXunbc9cgtm+R/+psYsUJlgXhU9cTIpOCjcOiq23oz1Y06QNrVC33PQdJ7PeDSboU+t+OjTSAjAE6vKZnr7HSfwX7F13wJN/5wS2+UH7mlfPw+o9NuvGBbLS8HC28qBe3fGx7J6b+WgCXkjRO71hKr1VBsn26kGWYohaGNeJOGwDQDTsz/4=
  file: "dist/docktor-${TRAVIS_TAG}.zip"
  on:
    tags: true
